AWSTemplateFormatVersion: 2010-09-09
Description: 'Billing Alerts for AWS Account - uses Input Parameters for alarm thresholds'

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Alarm Configuration"
        Parameters:
          - EmailAddress
          - AlarmThresholds
    ParameterLabels:
      EmailAddress:
        default: "What's your email address?"
      AlarmThresholds:
        default: "What dollar amounts to alert on?"

Parameters:

#Email Address used for SNS Topic subscription for Billing Alerts
  EmailAddress:
    Type: String
    Description: "Enter your email address for billing alerts"
    AllowedPattern: ^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$
#Numerical Thresholds - in $USD - for Billing alarms
  AlarmThresholds:
    Type: CommaDelimitedList
    Description: "Enter five (5) values for the billing alarms (e.g., 1,5,10,20,50)"

Resources:

#Create Billing Alerts based upon Parameter Thresholds
  BillingAlertOne:
    Type: AWS::CloudWatch::Alarm
    DependsOn: BillingAlertTopic
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [0, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [0, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [0, !Ref AlarmThresholds]

  BillingAlertTwo:
    Type: AWS::CloudWatch::Alarm
    DependsOn: BillingAlertTopic
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [1, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [1, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [1, !Ref AlarmThresholds]

  BillingAlertThree:
    Type: AWS::CloudWatch::Alarm
    DependsOn: BillingAlertTopic
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [2, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [2, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [2, !Ref AlarmThresholds]

  BillingAlertFour:
    Type: AWS::CloudWatch::Alarm
    DependsOn: BillingAlertTopic
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [3, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [3, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [3, !Ref AlarmThresholds]

  BillingAlertFive:
    Type: AWS::CloudWatch::Alarm
    DependsOn: BillingAlertTopic
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [4, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [4, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [4, !Ref AlarmThresholds]

#Create SNS Topic and Subscribe Email Address
  BillingAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "Billing-Alerts"
      Subscription:
      - Endpoint: !Ref EmailAddress
        Protocol: email
